// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.7.5
//   protoc               v3.20.3
// source: proto/orders.proto

/* eslint-disable */
import { GrpcMethod, GrpcStreamMethod } from "@nestjs/microservices";
import { Observable } from "rxjs";

export const protobufPackage = "orders";

export interface Empty {
}

export interface OrderRequest {
  productId: string;
  amount: number;
}

export interface OrderResponse {
  id: string;
  productId: string;
  amount: number;
  status: string;
  createdAt: string;
  updatedAt: string;
}

export interface GetOrdersResponse {
  orders: OrderResponse[];
}

export interface PaginationDto {
  page: number;
  limit: number;
}

export const ORDERS_PACKAGE_NAME = "orders";

export interface OrderServiceClient {
  createOrder(request: OrderRequest): Observable<OrderResponse>;

  /** rpc queryOrders(stream PaginationDto) returns (stream GetOrdersResponse); */

  getOrders(request: Empty): Observable<GetOrdersResponse>;
}

export interface OrderServiceController {
  createOrder(request: OrderRequest): Promise<OrderResponse> | Observable<OrderResponse> | OrderResponse;

  /** rpc queryOrders(stream PaginationDto) returns (stream GetOrdersResponse); */

  getOrders(request: Empty): Promise<GetOrdersResponse> | Observable<GetOrdersResponse> | GetOrdersResponse;
}

export function OrderServiceControllerMethods() {
  return function (constructor: Function) {
    const grpcMethods: string[] = ["createOrder", "getOrders"];
    for (const method of grpcMethods) {
      const descriptor: any = Reflect.getOwnPropertyDescriptor(constructor.prototype, method);
      GrpcMethod("OrderService", method)(constructor.prototype[method], method, descriptor);
    }
    const grpcStreamMethods: string[] = [];
    for (const method of grpcStreamMethods) {
      const descriptor: any = Reflect.getOwnPropertyDescriptor(constructor.prototype, method);
      GrpcStreamMethod("OrderService", method)(constructor.prototype[method], method, descriptor);
    }
  };
}

export const ORDER_SERVICE_NAME = "OrderService";
